// Generated by adsterra-code-handoff. Public browser configuration only.
// Domain: 100daysatsea.net
// Do not edit manually; rerun the handoff when placements change.
export const adsterraStaticConfig = {
  adsterraBannerId: "44a1435a2316502d476da4efccf9db95",
  adsterraBanner300x250Key: "44a1435a2316502d476da4efccf9db95",
  adsterraBanner300x250ScriptUrl: "https://www.highperformanceformat.com/44a1435a2316502d476da4efccf9db95/invoke.js",
  adsterraBanner320x50Key: "11557aed855b409db038d61969f58f03",
  adsterraBanner320x50ScriptUrl: "https://www.highperformanceformat.com/11557aed855b409db038d61969f58f03/invoke.js",
  adsterraBanner728x90Key: "de75e18c10654bf43a02b0d94edae6fa",
  adsterraBanner728x90ScriptUrl: "https://www.highperformanceformat.com/de75e18c10654bf43a02b0d94edae6fa/invoke.js",
  adsterraNative1Id: "container-f708eba700d8024e0d8f0767af5cfda8",
  adsterraNative1ScriptUrl: "https://pl30200444.effectivecpmnetwork.com/f708eba700d8024e0d8f0767af5cfda8/invoke.js",
  adsterraLeaderboardId: "de75e18c10654bf43a02b0d94edae6fa",
  adsterraEnablePopunder: false,
  adsterraEnableSocialBar: false,
  adsterraEnableStickyRail: false,
  adsterraPopunderDelayMs: 30000,
  adsterraPopunderMinPageViews: 2,
} as const;

export const adsterraStaticEnv = {
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_KEY: "44a1435a2316502d476da4efccf9db95",
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_SCRIPT_URL: "https://www.highperformanceformat.com/44a1435a2316502d476da4efccf9db95/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_KEY: "11557aed855b409db038d61969f58f03",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_SCRIPT_URL: "https://www.highperformanceformat.com/11557aed855b409db038d61969f58f03/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_KEY: "de75e18c10654bf43a02b0d94edae6fa",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_SCRIPT_URL: "https://www.highperformanceformat.com/de75e18c10654bf43a02b0d94edae6fa/invoke.js",
  NEXT_PUBLIC_ADSTERRA_ENABLE_POPUNDER: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_SOCIAL_BAR: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_STICKY_RAIL: "false",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_ID: "container-f708eba700d8024e0d8f0767af5cfda8",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_SCRIPT_URL: "https://pl30200444.effectivecpmnetwork.com/f708eba700d8024e0d8f0767af5cfda8/invoke.js",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_DELAY_MS: "30000",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_MIN_PAGEVIEWS: "2",
} as const;
